In [2]:
import numpy as np


In [8]:
arr = np.array(((1,2),(3,4))) # value , datatype
print(arr)
print(arr.ndim)  #attribute
print(arr.shape)
print(type(arr))
print(arr.dtype)


[[1 2]
 [3 4]]
2
(2, 2)
<class 'numpy.ndarray'>
int64


In [12]:
#methods 
arr = np.array(((1,2),(3,"ABC"))) # value , datatype
print(arr)
print(arr.ndim)  #attribute

print(np.arange(3)) #start stop step
print(np.random.rand(23))
print(np.random.rand(1,2))
print(np.random.randint(0,10,12)) #start , end  element

[['1' '2']
 ['3' 'ABC']]
2
[0 1 2]
[0.03943904 0.29109569 0.38616983 0.08445365 0.10841523 0.5804106
 0.54256026 0.20032828 0.44689627 0.60584867 0.86376636 0.53856378
 0.6359075  0.2469084  0.12460182 0.46633274 0.95754305 0.51482169
 0.58708242 0.99513961 0.38203351 0.38694827 0.27686997]
[[0.81170347 0.24083126]]
[8 9 6 8 4 4 5 3 6 6 6 5]


In [13]:
#create a guessing game where uesr will enter a number you have tell number is big or small
#loop user guess another number untillit win

num = np.random.randint(0,10)
user = int(input("enter a number :"))
while(num != user):
    user = int(input("enter a number :"))
    if (num == user):
        print("you won")
    elif(num>user):
        print("guess a large number")
    else:
        print("guess a small number ")

guess a small number 
guess a small number 
you won


In [ ]:
#zeros
print(np.zeros((3,4,2), dtype = int) )

#ones
print(np.ones((3,4,2), dtype = int))

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [21]:
arr = np.random.randint(1,10,12)
print(arr)
print(arr.shape)
print(arr.reshape(3,4))
print(arr)

[6 5 1 6 3 9 5 7 8 4 7 2]
(12,)
[[6 5 1 6]
 [3 9 5 7]
 [8 4 7 2]]
[6 5 1 6 3 9 5 7 8 4 7 2]


In [ ]:
arr+arr #operator overloading

array([12, 10,  2, 12,  6, 18, 10, 14, 16,  8, 14,  4], dtype=int32)

In [23]:
list1 = [1,2,3,4]
list1+list1

[1, 2, 3, 4, 1, 2, 3, 4]

In [36]:
#max , min, argmax, argmin
max(arr) #python function
print(arr)
arr.max() #numpy method
max(list1)
print(list1)

arr.min()
arr.argmax()
arr.argmin()
arr.mean()
arr.std()


[6 5 1 6 3 9 5 7 8 4 7 2]
[1, 2, 3, 4]


np.float64(2.3139072294858036)

In [39]:
arr[3] #indexing
arr[:5] #slicing

array([6, 5, 1, 6, 3], dtype=int32)

In [41]:
np.arange(1,30,2).size

15